### ISSUE TITLE
Mismatch of return order vs. comments in iterative_stratification

### ISSUE THREAD

**Issue by willjobs** [scikit-multilearn-ng/scikit-multilearn-ng#25]
The comment about what `iterative_train_test_split` returns is misleading. The comment says the order of objects returned is `X_train, y_train, X_test, y_test`, but it actually returns `X_train, X_test, y_train, y_test`.

I think this came over from the `master` branch of the original `scikit-multilearn`. On the master branch you see the same mismatch. Interestingly, they "fixed" this in v0.2.0 [here](https://github.com/scikit-multilearn/scikit-multilearn/blob/23c47317b19f0477eb97819c6717eaec85fc44fd/skmultilearn/model_selection/iterative_stratification.py#L98), but that fix never made its way into the master branch.

To summarize, we have:
* `scikit-multilearn` latest release: comment + code match in returning `X_train, y_train, X_test, y_test`
* `scikit-multilearn` master branch, and `scikit-multilearn-ng`:
    * code returns `X_train, X_test, y_train, y_test`, comment says it returns `X_train, y_train, X_test, y_test`
* `scikit-learn`'s original [train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) returns `X_train, X_test, y_train, y_test`, so I think that's the expected behavior by folks new to `scikit-multilearn`.

So if you want to align with the `scikit-learn`, I think you just need to update the comment [here](https://github.com/scikit-multilearn-ng/scikit-multilearn-ng/blob/07d7e44d2613d9abd8a697702c4e0215dfad19d2/skmultilearn/model_selection/iterative_stratification.py#L104). But if you want to align with the latest release of `scikit-multilearn`, you'd want to update the return statement.

I'd be happy to make the PR if you tell me which you'd prefer :)

https://github.com/scikit-multilearn-ng/scikit-multilearn-ng/blob/07d7e44d2613d9abd8a697702c4e0215dfad19d2/skmultilearn/model_selection/iterative_stratification.py#L102-L121

**Comment by northern-64bit** [comment]
Hello @willjobs,

Thank you for bringing this to our attention and for your thorough investigation into the discrepancies between the `iterative_train_test_split` documentation and its actual behavior.

Long-term, our objective is indeed to mirror the usability found in `scikit-learn`, as this simplifies the learning curve for new users. You can see this reflected in our documentation here: [`scikit-multilearn-ng` usage example](https://scikit-multilearn-ng.github.io/scikit-multilearn-ng/_static/example_usage.html).

Although this will be a breaking change when transitioning from `scikit-multilearn`  to `scikit-multilearn-ng`. However considering the potential impact on existing `scikit-multilearn-ng` users who are accustomed to the current order, I propose we update the documentation to accurately reflect the current implementation rather than adjusting the code to match the documentation. This approach minimizes disruption for our current user base while clarifying expectations for new users.

I appreciate your offer to help by making a pull request. Please go ahead with openening a PR updating the comment in the documentation to match the actual behavior (`X_train, X_test, y_train, y_test`). Let me know if you need any assistance.

Thanks again for your contribution and keen eye on this issue!
